--- #YAML:1.0
name: DateTime-Calendar-Japanese
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  DateTime::Calendar::Chinese: 0
  DateTime::Calendar::Japanese::Era: 0
  DateTime::Event::Sunrise: 0
  Params::Validate: 0
recommends:
  perl: 5.6.1
build_requires: {}
conflicts: {}
provides:
  DateTime::Calendar::Japanese:
    file: lib/DateTime/Calendar/Japanese.pm
    version: 0.01
generated_by: Module::Build version 0.21
