--- #YAML:1.0
name: DateTime-Calendar-Japanese
version: 0.03
author:
  - Daisuke Maki E<lt>daisuke@cpan.orgE<gt>
abstract: |-
  DateTime Extension for Traditional Japanese Calendars
license: perl
requires:
  DateTime: 0
  DateTime::Calendar::Chinese: 0.02
  DateTime::Calendar::Japanese::Era: 0.04
  DateTime::Event::Sunrise: 0
  Params::Validate: 0
recommends:
  perl: 5.6.1
build_requires: {}
conflicts: {}
provides:
  DateTime::Calendar::Japanese:
    file: lib/DateTime/Calendar/Japanese.pm
    version: 0.03
generated_by: Module::Build version 0.22
